---
image: docker:stable

variables:
  PUPPET_SERVER_VERSION: "2.6.0-1puppetlabs1"
  CONTAINER_IMAGE: docker-registry.spbtv.com/puppetserver-standalone

build:
  stage: build
  script:
    - docker build --rm --force-rm --pull --tag $CONTAINER_IMAGE:$PUPPET_SERVER_VERSION.$CI_JOB_ID --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$PUPPET_SERVER_VERSION.$CI_JOB_ID
    - docker push $CONTAINER_IMAGE:latest
