---
image: docker:stable

stages:
  - build
  - push

variables:
  CONTAINER: puppetserver-5
  REGISTRY: docker-registry.spbtv.com

build:
  stage: build
  script:
    - docker build --rm --force-rm --pull --tag $CONTAINER:latest .

push:
  stage: push
  only:
    - tags
  scripts:
    - docker tag $CONTAINER:latest $CONTAINER:$CI_COMMIT_TAG
    - docker push $CONTAINER:latest
    - docker push $CONTAINER:$CI_COMMIT_TAG
