---
image: docker:stable

variables:
  PUPPET_SERVER_VERSION: "2.6.0"
  DOCKER_REGISTRY: docker-registry.spbtv.com
  CONTAINER_IMAGE: puppetserver-standalone

build:
  stage: build
  script:
    - docker build --rm --tag $CONTAINER_IMAGE:$PUPPET_SERVER_VERSION.$CI_JOB_ID .
    - docker tag $CONTAINER_IMAGE:$PUPPET_SERVER_VERSION.$CI_JOB_ID $DOCKER_REGISTRY/$CONTAINER_IMAGE:$PUPPET_SERVER_VERSION.$CI_JOB_ID
    - docker tag $CONTAINER_IMAGE:$PUPPET_SERVER_VERSION.$CI_JOB_ID $DOCKER_REGISTRY/$CONTAINER_IMAGE:latest
    - docker push $DOCKER_REGISTRY/$CONTAINER_IMAGE:$PUPPET_SERVER_VERSION.$CI_JOB_ID
    - docker push $DOCKER_REGISTRY/$CONTAINER_IMAGE:latest
